name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Configure ESP32 board support
      run: |
        arduino-cli config init
        arduino-cli config set board_manager.additional_urls https://dl.espressif.com/dl/package_esp32_index.json
        arduino-cli core update-index

    - name: Install ESP32 core
      run: arduino-cli core install esp32:esp32

    - name: Install libraries
      run: |
        # Replace "YourLibrary" with the actual names of the libraries you need
        # arduino-cli lib install "YourLibrary"
        arduino-cli lib install "ArduinoJson"

    - name: Compile sketch
      run: |
        # Replace "YourSketch/YourSketch.ino" with the path to your main sketch file
        # The FQBN (Fully Qualified Board Name) for a generic ESP32 is esp32:esp32:esp32
        arduino-cli compile --fqbn esp32:esp32:esp32 YourSketch/YourSketch.ino --output-dir ./build

    - name: Upload firmware binary
      uses: actions/upload-artifact@v3
      with:
        name: esp32-firmware
        path: |
          ./build/YourSketch.ino.bin
          ./build/YourSketch.ino.partitions.bin
